export const displayOptions = [
  { displayType: 0, displayComponent: null },
  { displayType: 1, displayName: "WBW", displayComponent: "WBWDisplay" },
  { displayType: 2, displayName: "Normal", displayComponent: "NormalDisplay" },
  { displayType: 3, displayName: "Continuous", displayComponent: "ContinuousNormalDisplay" },
  { displayType: 4, displayName: "Side By Side", displayComponent: "SideBySideDisplay" },
];

export const selectableVerseTranslations = {
  1: {
    id: 1,
    language: "Arabic",
    author: "Transliteration (Tajweed)",
    slug: "arb_transliteration_tajweed",
  },
  10: {
    id: 10,
    language: "English",
    author: "Hilali & Khan",
    slug: "eng_muhammadtaqiudd",
  },
  11: {
    id: 11,
    language: "English",
    author: "Sahih International",
    slug: "eng_ummmuhammad",
  },
  12: {
    id: 12,
    language: "English",
    author: "Abul Alaa Maududi",
    slug: "eng_maududi",
  },
  13: {
    id: 13,
    language: "English",
    author: "Pickthall",
    slug: "eng_mohammedmarmadu",
  },
  14: {
    id: 14,
    language: "English",
    author: "Yusuf Ali",
    slug: "eng_yusufaliorig",
  },
  15: {
    id: 15,
    language: "English",
    author: "The Clear Quran (Mustafa Khattab)",
    slug: "eng_mustafakhattaba",
  },
  16: {
    id: 16,
    language: "English",
    author: "Abdel Haleem",
    slug: "eng_abdelhaleem",
  },
  17: {
    id: 17,
    language: "English",
    author: "Almuntakhab Fi Tafsir Alquran Alkarim",
    slug: "eng_almuntakhabfita",
  },
  18: {
    id: 18,
    language: "English",
    author: "Mufti Taqi Usmani",
    slug: "eng_muftitaqiusmani",
  },
  19: {
    id: 19,
    language: "English",
    author: "Tahfeem-ul-Quran by Abul Alaa Maududi",
    slug: "eng_tafheem",
  },
  20: {
    id: 20,
    language: "English",
    author: "Tafsir al-Jalalayn",
    slug: "eng_jalalayn",
  },
  30: {
    id: 30,
    language: "Urdu",
    author: "Ahmed Ali",
    slug: "urd_ahmedali",
  },
  31: {
    id: 31,
    language: "Urdu",
    author: "Abul Alaa Maududi",
    slug: "urd_abulaalamaududi",
  },
  32: {
    id: 32,
    language: "Urdu",
    author: "Muhammad Junagarhi",
    slug: "urd_muhammadjunagar",
  },
  33: {
    id: 33,
    language: "Urdu",
    author: "Abul Alaa Maududi",
    slug: "urd_abulaalamaududi_la",
  },
  34: {
    id: 34,
    language: "Hindi",
    author: "Suhel Farooq & Saifur Rahman",
    slug: "hin_suhelfarooqkhan",
  },
  35: {
    id: 35,
    language: "Hindi",
    author: "Suhel Farooq & Saifur Rahman",
    slug: "hin_suhelfarooqkhan_la",
  },
  36: {
    id: 36,
    language: "Indonesian",
    author: "Indonesian Islamic Affairs Ministry",
    slug: "ind_indonesianislam",
  },
  37: {
    id: 37,
    language: "Bangla",
    author: "Zohurul Hoque",
    slug: "ben_zohurulhoque",
  },
  38: {
    id: 38,
    language: "Bangla",
    author: "Muhiuddin Khan",
    slug: "ben_muhiuddinkhan",
  },
  39: {
    id: 39,
    language: "Turkish",
    author: "Diyanet Isleri",
    slug: "tur_diyanetisleri",
  },
  40: {
    id: 40,
    language: "Turkish",
    author: "Elmalili Hamdi Yazir",
    slug: "tur_elmalilihamdiya",
  },
  41: {
    id: 41,
    language: "Tamil",
    author: "Jan Turst Foundation",
    slug: "tam_janturstfoundat",
  },
};
